name: cdth_consumer_text
channels:
  - conda-forge
dependencies:
  - python=3.7
  - jupyter
  - spacy=2.2.2
  - ipywidgets
  - pip
  - pip:
    - ibis-framework[mysql]
    - spacy-readability
    - medspacy==0.0.1.1
    - https://github.com/abchapman93/spacy_models/raw/master/releases/en_info_3700_i2b2_2012-0.1.0/dist/en_info_3700_i2b2_2012-0.1.0.tar.gz
